-- phpMyAdmin SQL Dump
-- version 5.0.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 05, 2021 at 12:18 PM
-- Server version: 10.4.14-MariaDB
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `konacno`
--

-- --------------------------------------------------------

--
-- Table structure for table `muzej`
--

CREATE TABLE `muzej` (
  `id` int(11) NOT NULL,
  `cover_photo` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `short_description` varchar(255) NOT NULL,
  `content` longtext NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `category` int(11) NOT NULL,
  `main_category` int(11) DEFAULT NULL,
  `year` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `muzej`
--

INSERT INTO `muzej` (`id`, `cover_photo`, `title`, `short_description`, `content`, `created_at`, `deleted`, `category`, `main_category`, `year`) VALUES
(1, 'teodolit1.jpg', 'Ertel & Sohn, 1900', 'Instrument hrani podjetje Geoservis d.o.o', '<p>Teodolit sodi v čas okrog leta 1900. Na horizontalnem krogu je vgravirana razdelba z natančnostjo 20 minut. Dva med seboj deiametralno nasproti nameščena nonija in lupi za odčitavanje omogočajo natančnost merjena kotov na eno minuto. 360-stopinjska razdelba na vertikalnem krogu je vgravirana z isto natančnostjo kot razdelba na horizontalnem krogu, s pomočjo dveh nonijev in nad noniji nameščenima lupama pa daje odčitke na 1 minuto natančno. Oba kroga sta zaščitena v kovinskem ohišju. Daljinogled s 17-kratno povečavo ima vgrajen Reichenbachov nitni križ in deluje s pomočjo izvlečenega okularja. Za horizontiranje instrumenta sta na instrumentu dve cevni libeli, nameščeni pravokotno ena na drugo. Za določanje mesta čitanja na vertikalnem krogu je nameščena zavarovana libea. Instrument ima za grobo horizontiranje nameščeno dozno libelo.</p>', '2020-11-11 22:48:24', 0, 1, NULL, 1900),
(2, 'teodolit2.jpg', 'Gebruder Fromme, 1900', 'Instument hranijo na FGG pri Univerzi v Ljubljani', 'Teodolit je bil izdelan v zadnjih letih 19. stoletja. Odčitivanje horizontalnega kroga omogočata diametralno nasproti nameščena nonija, nad katerima sta nameščeni lupi. Natančnost odčitavanja kota je 1 minuta, nonij je razdeljen na 20 delov. Odčitivanje vertikalnega kroga omogoča nonij, ki je nameščen na najvišjem delu 360-stopinjskega kroga, in nad njim pritrjene lupe. Instrumentu je dodana busola. Za horizontiranje instrumenta sta na alhidadi pravokotno ena na drugo nameščeni cevni libeli. Instrument ima na daljinogledu nameščeno tudi nivelacijsko libelo. Tako vertikalni kot horizontalni krog sta vidna v celoti. V daljinogledu, ki ima 17-kratno povečavo, je nameščen trinitni razdaljemer. Daljinogled ima zunanje fokusiranje. IzIz elaboratov, povezanih z vzdržavanjem zemljiškega katastra , je razvidno, da se je instrument uporabljal še 50.letih prejšnjega stoletja. ', '2020-11-11 22:55:35', 0, 1, NULL, 1900),
(3, 'teodolit3.jpg', 'Carl Bamberg, 1880', 'Instrument hrani Naravoslovnotehniška fakulteta pri UL', 'Posebnost tega instrumenta je v tem, da je daljinogled nameščen na zunanjem delu horizontalne osi. Instrument ima vgravirano razdelbo na medeninastih krogih, katerih natančnost je 1 minuta. Vrednost razdelbe na nonijupri vertikalnem in horizontalnem krogu je 10 minut. Za odčitavanje vsakega kroga sta nameščeni po dva nonija, iznad katerih so pritjene lupe. Vertikalni krog je še popolnoma odprt, medtem ko je horizontalni še zaščitenpred poškodbami v kovinskem ohišju. Za horizontiranje instrumenta je nameščena če ena cevna libela. V daljinogledu je nameščen trinitni razdeljemer, povečava daljinogleda je 17-kratna. ', '2020-11-11 22:56:56', 0, 1, NULL, 1880),
(4, 'teodolit4.jpg', 'Starke & Kammerrer, 1890', 'Instrument je v zasebni zbirki', 'Teodolit je iz 90. letih 20. stoletja. Na horizontalnem krogu, ki je zašćiten v kovinskem ohišju, je vgravirana razdelba z natančnostjo 20 minut. Nonij in lupa za odčitavanje omogočata natančnost merjenja kotovna 1 minuto. Razdelba na tretjinskem vertikalnem krogu je vgravirana z isto natančnostjo kot razdelba na horizontalnem krogu, s pomočjo nonija in lupe, nameščene nad nonij, pa daje odčitke na 1 minuto natančno.Razdelbi na obeh krogih sta vgravirana na kovinskem obroči iz srebra. Daljinogled s 17-kratno povečavo ima vgrajen Reichenbachov nitni križ. Iz arhiva zemljiškega katastra je razvidno, da so te instrumente uporabljalipri vzdrževanju zemljiškega katastra vse do sredine 60. let prejšnjega stoletja. ', '2020-11-11 22:58:26', 0, 1, NULL, 1890),
(5, 'teodolit5.jpg', 'Wild Heerbrugg, 1924', 'Instrument hrani podjetje Geoservis d.o.o', 'Wild T2\r\nTeodolit je prvi iz serije instrumentov Wild T2. Izdelan je bil leta 1924. Vrhunski dosežek Wildovih konstruktorjev se je održal v  natančnem sekundnem instrumentu z vgrajenim staklenimi diski. Premer horizontalnega kroga je bil 90 mm in vertikalnega 45 mm. Prvič se je pri instrumentih pojavil mikroskop za odčitavanje kotov vzporedno z okularjem daljinogleda. Razdelba kotov je vgravirana z natančnostjo 20 sekund, s pomočjo vgrajenega mikrometra je omogočeno neposredno odčitavanje na sekundo natančno, z oceno pa na 0.1 sekunde. Instrument je omogočal osvetlitev horizontalnih in vertikalnih krogov tudi z umetno svetlobo.', '2020-11-11 23:10:48', 0, 1, NULL, 1924),
(6, 'teodolit6.jpg', 'Breithaupt & Sohn, Kassel 1920', 'Instrument hrani podjetje Geoservis d.o.o', 'Razdelba na horizontalnem limbu je 10-minutna, vertikalni krog pa ima 20-minutno razdelbo, vgravirano na kovinska kroga, ki sta dokaj dobro zaščitena pred atmosferskimi vplivi. Odčitavanje horizontalnih in vertikalnih krogov omogočata po dva nonija na krog. Natančnost odćitavanja krogov je ena minuta. Za lažjo in večjo čitljivost odčitavanja so nad noniji nameščene lupe. Za horizontiranje sta na instrumentu nameščeni cevna in dozna libela. Na daljnogledu z Reichenbachovim razdaljemerom je nameščena nivelacijska libela, za določanje mesta čitanja na vertikalnem krogu je nameščena še zavarovalna libela. Na stranskem ohišju neposredno pod vertikalnim krogom je magnetna igla. Instrument sodi v 20. leta prejšnjega stoletja.', '2020-11-12 00:56:09', 0, 1, NULL, 1920),
(7, 'teodolit7.jpg', 'Neuhofer & Sohn, Wien 1900', 'Instrument hrani Tehniški muzej Slovenije', 'Instrumentu je dodana busola. Razdelba horizontalnega kroga in polovičnega vertikalnega kroga je s 30-minutno natančnostjo vgravirana na kovinski material. Noniji omogočajo minutno natančnost odčitavanja. Za merjenje dolžin ima daljinogled vgraviran Reichenbachov nitni križ. Horizontiranje instrumenta omogočajo trije vznožni vijaki in dve medsebojno pravokotno nameščeni cevni libeli. Na daljinogledu je nameščena nivelacijska libela. Po serijski številki instrumenta sklepamo, da je bil arhivski eksponat izdelan v začetku prejšnjega stoletja.', '2020-11-11 23:28:28', 0, 1, NULL, 1900),
(8, 'teodolit8.jpg', 'Trimble Navigation, 2015', 'Instrument je v lasti Geodetske uprave Republike Slovenije', 'V letu 2015 je ameriško podjetje Trimble predstavilo najnovejši geodetski GNSS-instrument, model R10, ki je prvi instrument nove generacije s t. i. HD-GNSS-tehnologijo. Tehnologija omogoča hitrejše izvajanje meritev in nadomešča klasično \"fixed/float\" tehniko inicijalizacije. Vgrajeno ima tudi kompenzacijo nagiba instrumenta. Satelitske signale sprejema na 440 kanalih, masa instrumenta z baterijo je 1.12 kg, ena baterija omogoča 5 ur neprekinjenih meritev. ', '2020-11-11 23:43:55', 0, 1, NULL, 2015),
(9, 'teodolit9.jpg', 'Carl Zeiss Jena, 1970', 'Instrument hrani Območna geodetska uprava Novo Mesto', 'V času razvoja novega avtoredukcijskega tahimetra Dahlta je podjetje razvilo tudi kartirno mizo Karti 250, ki jo je bilo mogoče uporabljati že pri instrumentu Theo 030, predvsem pa ob avtoredukcijskem tahimetru Dahlta in Redta 002.\r\n\r\nInstrument omogoča neposredno polavtomatsko kartiranje polarno posnetega detajla na terenu. Tako je ta instrument prevzel vlogo predhodne kartirne mizice. Ta kombinacija instrumentov je bila primerna za katastrska merjenja, topografska snemanja in dopolnjevanje fotogrametričnih snemanj. Prvotni premer kartirne plošče je bil 160 mm, nato 200 mm, nazadnje so jo povečali na 250 mm. Delovanje mizice je enostavno. Karti je neposredno povezano z alhidado instrumenta, tako da se ob obračanju teodolita obrača tudi gibljivi del (risalni del) instrumenta Karti. Operator na lati odčitano dolžino s pomočjo nanašalnega ravnilca (h Karti so priložena ravnilca za različna merila) na kartirno ploščo nanese odčitano dolžino, pri tem pa se vizura prenaša avtomatsko. S tem se v veliki meri medsebojno dopolnjuje prednost grafične in numerične tahimetrije.', '2020-11-12 00:17:27', 0, 1, NULL, 1970),
(10, 'teodolit10.jpg', 'Carl Zeiss Jena, 1960', 'Arhivski primerek je shranjen na Območni geodetski upravi Celje', 'Ta mali teodolit je bil primeren za vsa geodetska dela pri vzdrževanju zemljiškega katastra. Zaradi svoje majhnosti je bil še najbolj priročen pri meritvah v zaraščenem terenu. Instrument ima mikrometrsko skalo za odčitavanje vertikalnega in horizontalnega kroga, ki se odslikava prek mikroskopa, nameščenega neposredno ob okular daljnogleda. Natančnost neposrednega odčitavanja horizontalnega in vertikalnega kroga je 10 minut, z oceno pa na 1 minuto natančno. Za odmero dolžin je v daljnogledu vgrajen Reichenbachov križ. Povečava daljnogleda je 16-kratna. Najkrajša vidna razdalja je 0.9 m. Premer horizontalnega in vertikalnega kroga je 61 mm. Teodolit ima natakljivo busolo. Proizvodnja teh instrumentov je potekala v 60. letih prejšnjega stoletja.', '2020-11-12 00:24:03', 0, 1, NULL, 1960),
(11, 'teodolit.jpg', 'TEODOLITI', 'Instrumenti za merjenje in zakoličevanje horizontalnih in vertikalnih kotov, ali zenitnih razdalj', '', '2020-11-26 23:10:09', 0, 2, 1, 0),
(12, 'nivelir.jpg', 'NIVELIRJI', 'Uporabljajo se za natančno merjenje višinskih razlik', '', '2020-11-26 23:11:48', 0, 2, 3, 0),
(13, 'ostalo.jpg', 'DRUGI INSTRUMENTI', 'Drugi instrumenti, oprema in geodetska orodja za merjenje količin v geodeziji', '', '2020-11-26 23:12:59', 0, 2, 4, 0),
(14, 'teodolit11.jpg', 'Breithaupt & Sohn, Kassel, 1930', 'Instrument hrani glavni urad Geodetske uprave Republike Slovenije', '<p>Razstavni eksponat je hranila Geodetska uprava Maribor, meritve pa z njim opravljala v 50. in 60. letih prejšnjega stoletja, izdelan je bil verjetno pred drugo svetovno vojno. To podjetje je teodolit s horizontalnim (zaščitenim pred zunanjimi vremenskimi in mehaničnimi vplivi) in vertikalnim krogom (sicer še nezaščitenim)ter natakljivo busolo dala na trg že leta 1866. Razdelba na horizontalnem in vertikalnem krogu je vgravirana na kovinskem krogu in sorazmerno dobro zaščitena pred atmosferskimi vplivi. Odčitavanje horizontalnih in vertikalnih krogov omogočata po dva nonija na krog. Za lažjo in boljšo čitljivost odčitavanja so nameščene lupe. Instrument daje, glede na dvojno odčitavanje krožnih razdelb, za vsako opazovanje po dva podatka, katerih aritmetična sredina odpravlja morebitne pogreške pri ekscentričnosti krogov in ekscentričnosti vizure. Podoben instrument se je uporabljal pri vzdrževanju zemljiškega katastra tudi na območju Slovenj Gradca.</p>', '2020-12-09 12:24:52', 0, 1, NULL, 1930),
(15, 'teodolit12.jpg', 'Breithaupt & Sohn, Kassel, 1940', 'Instrument je v zasebni zbirki Gašperja Dimca iz Domžal', 'Instrument je posodobljenja izvedba njegovega predhodnika iz 30. let prejšnjega stoletja. Značilnosti instrumenta so podobne predhodniku, vendar so pri konstrukciji že uporabljeni lažji materiali (aluminij). Instrument je bolj priročen in uporabnejši pri vsakdanjih meritvah.\r\n\r\nPodobni instrumenti se pojavljajo pri vzdrževanju zemljiškega katastra na območju vseh geodetskih uprav v Sloveniji vse do do poznih 60 let prejšnjega stoletja. ', '2020-12-09 12:29:30', 0, 1, NULL, 1940),
(16, 'teodolit13.jpg', 'Carl Zeiss Jeena, 1930', 'Arhivski primerak hranijo v Muzeju premogovništva Slovenija v Velenju .', 'Th IV. Slika Th IV odraža stanje instrumenta, tik preden je šel iz uporabe. Instrument se je uporabljal ne samo pri vzdrževanju zemljiškega kastastra, temveč tudi pri drugih geodetskih delih (inženirska geodezija, rudarstvo, gozdarstvo). Najkrajša vidna razdalja daljnogleda je 1.8 m. Premer horizontalnega kroga je 89 mm in vertikalnega kroga 70 mm. ', '2020-12-09 12:34:21', 0, 1, NULL, 1930),
(17, 'teodolit15.jpg', 'Carl Zeiss Jena, 1953', 'Instrument hrani glavni urad Geodetske uprave Republike Slovenije', 'Instrumenti so se na trgu pojavili leta 1953, Dahlta nosi ime po norveškem konstruktorju J.Dahlu. Ti instrumenti še niso poznali izboljšav, ki so jih imeli poznejši instrumenti, kot so na primer povečava slike v daljnogledu, vgradna izboljšanega objektiva z večjo ostrino, modra optika, dva vertikalna limba (ločeno vertikalni krog in krog z diagramom krivulj), prosto vidno polje za odčitavanje vertikalnega kroga, osvetlitev obeh krogov z zrcalom, ki se obrača in nagiba, pokončna slika, polna slika (pri avtoredukcijskih tahimetrih Hammer-Fennel je bilo vidno polje omejeno na polovico) in možnost prisilnega centriranja. Delovanje diagramskega tahimetra temelji na zamisli prof. Hammerja iz Stuttgarta. Namesto togih oznak za merjenje dolžin in višinskih razlik se v ravnino slike okularja preslikava par krivvulj, katerih razmik se menja glede na višinski kot. To rešitev je prvo uporabilo podjetje Fennel iz Kassla v tahimetru Hammer-Fennel.\r\nZa merjenje dolžin in višinskih razlik so se uporabljale tako imenovanje late \"dahlta\" (late z reperjem na višini 1.40 mm). Instrument omogoča neposredno odčitavanje horizontalnih dolžin in višinskih razlik. Sledila je serija z oznako Dahlta 010 v letu 1968, nato Dahtla 010A v letu 1971, zadnji tip tega instrumenta z oznako Dahtla 010B pa se je na trgu pojavil v poznih 80. letih prejšnjega stoletja. ', '2020-12-09 13:51:40', 0, 1, NULL, 1953),
(18, 'teodolit16.jpg', 'Carl Zeiss Jena, AGA Geodimeter, 1970; 1977', 'Instrument v takšni kombinaciji hrani Območna geodetska uprava Maribor', 'Theo 010 A in AGA Geodimeter 12A\r\nTheo 010 A, sekundni teodolit iz serije Theo 010, je precej posodobljen glede na svojega predhodnika. Theo 010 so začeli proizvajati leta 1955, leta 1971 pa so na trg prišli prvi teodoliti Theo 010 A. Odčitavanje kotov, tako horizontalnega kot vertikalnega, omogoča poseben gumb na ohišju teodolita, ki se obrača v eno ali drugo smer. Novost glede na predhodnika Theo 010 je v izboljšavi - racionalizaciji namestitve gumbov za grobo in fino viziranje teodolita (nameščeno na enem mestu). AGA Geodimeter je elektrooptični razdeljemer, ki jih je v začetku 70. let prejšnjega stoletja začelo izdelovati švedsko podjetje AGA. AGA Geodimeter 12 A je iz let 1977. Natančnost merjenja dolžin je 5 mm do 1000 m za eno prizmo do 3000 m s trojno prizmo. Razdeljemer se je uporabljal kot samostojna enota, ki je bil v tem primeru s posebnim vmesnikom nameščen na sekundnem teodolitu Theo 010 A.', '2020-12-09 14:09:58', 0, 1, NULL, 1970),
(19, 'teodolit14.jpg', 'Carl Zeiss Jena, 1950', 'Instrument hrani glavni urad Geodetske uprave Republike Slovenije ', 'Theo 030\r\nTahimeter teodolit Theo 030 je izdelek podjetja Carl Zeiss Jena in je nastal na podlagi izkušenj s predhodnimi instrumenti. Pri konstrukciji daljnogleda je bil narejen revolucionarni premik. Daljnogled, katerega natančnost je enaka daljnogledu pri teodolitu Th IV, je skoraj za pol manjši. Teodolit je namenjen za vsa geodetska dela, ima vgrajeno repeticijo, natančnost neposrednega odčitavanja kotov z mikrometrom je 1 minuta, ocena na desetinko minute. Za merjenje dolžin se uporablja Reichenbachov nitni križ. Instrument ima vgrajene staklene kroge, ki so zaščiteni pred prahom in vlago, dodana je krogelna busola. V kompletu je podjetje ponujalo še dodatek za opazovanja strmih vizu, ki se je namestil na okular daljnogleda in mikroskopa za odčitavanje kotov. <p<ovečava daljnogleda je 25-kratna. Premer horizontalnega kroga je 96 mm in vertikalnega kroga 74 mm. Instrument je predhodnik instrumenta Theo 020.', '2020-12-09 14:41:19', 0, 1, NULL, 1950),
(20, 'teodolit17.jpg', 'F. Weiland, Liebenwerda, Zeichen - und Messgeratefabrik, 1900', 'Arhivski primerek hranijo v Geodetski pisarni Žalec', 'F. Weiland, Liebenwerda\r\nTovarna tehničnih izdelkov, kot so merilni in geodetski instrumenti, poslovna enota Liebenwerda je bila ustanovljena leta 1882. Leto izdelave arhivskega instrumenta sodi v začetek 20. stoletja. Vertikalni krog in daljnogled sta nameščena na enostranskem nosilcu. Instrument ima vgrajeno busolo, katere razdelba nadomešča horizontalni krog. Za odčitavanje vertikalnega kroga sta nameščena dva nonija, 360 -stopinjska razdelba vertikalnega kroga je vgravirana na kovinski krog, ki je zaščiten z ohišjem instrumenta. Instrument ima za horizontiranje nemščeni dve libeli. Reichenbachov nitni križ, nameščen v okularju daljnogleda, omogoča odčitavanje odsekov na lati, ima multiplikacijsko konstanto 100 in adicijsko konstanto 0.28.\r\nInstrument te vrste se pojavlja pri vzdrževanju zemljiškega katastra na več lokacijah (npr. Slovenske Konjice, Žalec..)', '2020-12-09 14:50:27', 0, 1, NULL, 1900),
(21, 'teodolit18.jpg', 'Fennel, Kassel, 1920', 'Teodolit je v zasebni zbirki', 'Otto Fennel Sohne, teodolit št. 13633\r\nVeliki \"Otto Fennel\" teodolit izhaja iz časa okoli leta 1920. Razdelba na horizontalnem in vertikalnem krogu je vgravirana na posrebreni kovini. Za odčitovanje kotov so nad noniji nameščene lupe s 4-kratno povečavo. Za vsak krog sta nameščena po dva nonija. Razdelba na noniju omogoča 30-sekundno natančnost merjenja kotov (večina instrumentov iz tega obdobja razpolaga le z minutno natančnstjo). Instrument ima štiri libele - nivelacijsko libelo, zavarovalno libelo in dve medsebojno pravokotno nameščeni libeli za horizontiranje instrumenta. Dolžina daljnogleda je 21 cm in omogoča 17-kratno povečavo. Instrument z zunanjim fokusiranjem ima adicijsko konstanto 0.35 m. Posebnost tega instrumenta je, da se med transportom daljnogled skupaj z vertikalnim krogom odstrani od ohišja preostalega instrumenta in se ločeno shranjuje v posebnem ležiču.', '2020-12-09 15:00:33', 0, 1, NULL, 1920),
(22, 'teodolit19.jpg', 'Fennel, Kassel, 1940', 'Arhivski primerek hrani Fakulteta za gradbeništvo in geodezijo pri Univerzi v Ljubljani', 'Instrument ima nameščen le horizontalni krog, ki ga je mogoče opazovati prek dveh diametralno nasproti nameščenoh mikroskopov z mikrometrsko razdelbo. Za horizontiranje sta na ohišju/alhidadi instumenta pravokotno eno na drugo nameščeni dve cevni libeli. Instrument je opremljen z daljnogledom, ki omogoča neposredno odčitavanje na lati reducirane dolžine in relativne višinske razlike. V daljnogledu se na levi strani vidnega polja vidijo krivulje, na desni strani pa opazovani detajl. Daljnogled se navizira na lato na ničleno točko (običajno 1.4 m nad zemljo), ob krivuljah pa se odčitava horizontalna dolžina in relativna višinska razlika. Instrument nima vertikalnega kroga, dodan ima repeticijski vijak. Na daljnogledu je nameščena nivelacijska libela, daljnogled skupaj z libelo se lahko odstrani od preostalega ohišja insštrumenta. Te instrumente je podjetje izdelovalo takoj po drugi svetovni vojni.\r\n\r\nInstrument se je pri vzdrževanju zemljiškega katastra uporabljal tam, kjer je storitve opravlja takratni Geodetski zavod LRS.', '2020-12-09 15:17:13', 0, 1, NULL, 1940),
(23, 'teodolit20.jpg', 'Fennel, Kassel, 1950', 'Instrument je v zasebni zbirki Gašperja Dimca iz Domžal', 'Fennel št. 84315\r\n\r\nTeodolit sodi v 50. leta prejšnjega stoletja. Instrument ima oba kroga vgravirana na steklo. Za odčitavanje krogov je ob okularju daljnogleda nameščen mikrometer z razdelbo 5 minut. Instrumenti iz tega obdobja imajo poseben repeticijski vijak. Daljnogled s 24-kratno povečavo ima vgraviran Reichenbachov nitni križ (čeprav je bilo podjetje v tistem času eno od vodilnih, ki so v svoje instumente vgrejevali avtoredukcijske razdelbe) in nivelacijsko libelo. Za horizontiranje instrumenta sta nameščeni cevna in dozna libela, določanje mesta čitanja na vertikalnem krogu pa omogoča zavarovalna libela.\r\n\r\nInstrument se je pri vzdrževanju zemljiškega katastra uporabljal tam, kjer je storitve opravljal takratni Geodetski zavod LRS. ', '2020-12-09 15:28:42', 0, 1, NULL, 1950),
(24, 'teodolit21.jpg', 'Gebruder Fromme, 1890', 'Instrument hrani Območna geodetska uprava Nova Gorica', 'Teodolit je bil izdelan v zadnjih letih 19. stoletja. Za odčitavanje nonijske razdelbe vertikalnega in horizontalnega kroga je za vsak krog vgrajena lupa. Natančnost odčitavanje kotov je 1 minuta, razdelba nonija je 30 minutna. Za horizontiranje instrumenta sta na alhidadi nameščeni pravokotno ena na drugo cevni libeli. Instrument ima na daljnogledu nameščeno tudi nivelacijsko libelo. Tako vertikalni kot horizontalni krog sta vidna v celoti. 360 stopinjska razdelba vertikalnega limba je vgravirana na vertikalnem krogu. V daljnogledu s 17 kratno povečavo je nameščen trinitni razdaljemer. Daljnogled ima zunanje fokusiranje. \r\n\r\nIz elaboratov, povezanih z vzdrževanjem zemljiškega katastra, je razvidno, da se je instrument uporabljal na geodetski upravi v Novi Gorici še v 50. letih prejšnjega stoletja. ', '2020-12-09 15:35:44', 0, 1, NULL, 1890),
(25, 'teodolit22.jpg', 'Gustav HEYDE, Dresden, 1920', 'Instrument hrani Naravoslovnotehniška fakulteta pri Univerzi v Ljubljani (NTF)', 'Instrument sodi v 20. leta prejšnjega stoletja. Odčitavanje horizontalnega in vertikalnega kroga omogočajo diametralno nameščeni noniji, nad katerimi so nameščene lupe. Natančnost odčitavanja kota je 1 minuta, nonij je razdeljen na 30 delov. instrumentu je dodana busola. Za poravnanje vertikalnega kroga je nameščena zavarovalna libela. Horizontiranje instrumenta omogoćata na ohišju nad limbom horizontalnega kroga medsebojno pravokotno nameščeni cevni libeli. Instrument ima nameščen repeticijski vijak. Na daljnogledu teodolita je nameščena nivelacijska libela. Tako vertikalni kot horizontalni krog sta zaščitena v kovinskem ohišju instrumenta. V daljnogledu, ki ima 17-kratno povečavo, je nameščen trinitni razdeljemer. Daljnogled ima zunanje fokusiranje. Iz arhivov zemljiškega katastra ni neposredno zaznati, da bi bili instrumenti tega proizvajalca uporabljeni pri vzdrževanju zemljiškega katastra.', '2020-12-09 15:44:46', 0, 1, NULL, 1920),
(26, 'teodolit23.jpg', 'Hildebrand, prej August Lingke & Co, Freiberg na Saškem, 1900', 'Instrument je v zasebni zbirki Gašperja Dimca iz Domžal', 'Teodolit z naspisom na ohišju \"Hildebrand fruher August Lingke & Co, Freiberg in Sachsen\" je iz konca 90. let 19. stoletja. Instrument so razvili v znani finomehanični delavnici, ki jo je vodil Max Hildebrand. 360-razdelba je vgravirana na kovinskem vertikalnem krogu. Natančnost razdelbe vertikalnega kroga je 20 minut. S pomočjo nonija in nad nonijem nameščene lupe se vertikalni koti odčitavajo na 1 minuto natančno. Enako natančnsot dosega tudi horizontalni krog, ki ima nameščena dva med seboj diametralno nasproti ležeča nonija. Horizontiranje instrumenta omogoča ena sama cevna libela. Na daljnogledu, v katerem je nameščen trinitni razdeljemer, je nivelacijska libela.\r\n\r\nIz arhiva zemljiškega katastra je razvidno, da so se tovrstni instrumenti uporabljali pri vzdrževanju zemljiškega katastra tudi na naših tleh.', '2020-12-09 15:57:07', 0, 1, NULL, 1900),
(27, 'teodolit24.jpg', 'Kern, 1995', 'Arhivski primerek je Ljubljanski geodetski biro predal Tehniškem muzeju Slovenije - hrani ga glavni urad Geodetske uprave Republike Slovenije', 'Kern D4-RT\r\n\r\nPrve tovrstne teodolite so pri Kernu izdelali leta 1947, instrument na sliki je bil izdelan četa 1955. Sodi med avtoredukcijske tahimetre, ki omogočajo merjenje dožin s horizontalno lato (s pomočjo optične naprave  in dvojne slike). Instrument je po značilnosti podoben instrumentom Zeiss Redta in Wild RDH. Do razvoja elektonskih razdeljemerov so ti teodoliti spadali med najbolj natančne razdeljemere (natančnost merjenja od 1 do 2cm do dolžine 100 m).', '2020-12-09 16:02:11', 0, 1, NULL, 1995),
(28, 'teodolit25.jpg', 'Leica Geosystem, 1991', 'Instrument hrani Območna geodetska uprava Koper', 'Leica TC 1610\r\n\r\nTe instrumente je podjetje Leica proizvajalo od leta 1991 do 1995. Sodijo v zvrst kompaktnih elektronskih tahimetrov, katerih cena je bila sprejemljiva tudi za tisti čas. Natančnost merjenja horizontalnih kotov in vertikalnih kotov je 3 sekunde. Daljnogled, katerega dolžina je 196 mm, omgoča 30-kratno povečavo, najkrajša vidna dolžina je 1.7 m. Dolžine meri z natančnostjo 2 mm; 2 ppm do dolžine 2500 m na eno prizmo. S tremi prizmami meri razdalje do 5 km in z enajstimi prizmami do 7 km.', '2020-12-09 16:10:36', 0, 1, NULL, 1991),
(29, 'teodolit26.jpg', 'Leica Geosystem, 2004', 'Instrument je last podjetja Dimc d.o.o., Domžale', 'Leica TC 1205 + GPS\r\n\r\nLeica 2004 je Leica dala na trg TC 1205. Natančnost merjenja kotov je 5 sekund. Z eno prizmo je mogoče meriti do dolžine 3000 m, z mini prizmo do 1200 m, brez prizme pa daje dobre rezultate do 250 m. Natančnost merjenja dolžin na standardni način je 1 mm; 1.5 ppm, hitri način 3 mm, natančnost merjenja dolžin pri sledenju prizme je tudi 3 mm. Najmanjša dolžina, ki jo instrument še izmeri, je 1.5 m. Povečava daljnogleda je 30-kratna. Pomikanje instrumenta po horizontali in vertikali omogočata neskončna vijaka brez zaklepanj (brez grobega zaustavljanja premikanja daljnogeda okrog horizontalne oziroma vertikalne osi). Instrument ima možnost preklapljanja med stopinjsko in gradno razdelbo, kakor tudi med metrskim in čevljskim sistemom merjenja dolžin. LCD-zaslon je VGA (320X240 pik) in deluje na dotik, poleg zaslona je še tipkovnica s 34 tipkami. Instument ima 64 MB pomilnika (približno 60.000 točk), za prenos podatkov na drugi digitalni medij se uporablja vmesnik RS-232 oziroma je možna tudi povezava Bluetooth. Masa instrumenta je 4.8 kg. Instrument deluje brez težav pri -20°C do +50°C. Čas delovanja pri napolnjeni bateriji je 20 ur.\r\n\r\nNa sliki je instrument v kombinaciji z GPS 1200, ki zagotavlja fleksibilnost, moč in zanesljivost potrebno za vsako vrsto uporabe GPS.', '2020-12-09 16:34:45', 0, 1, NULL, 2004),
(30, 'teodolit27.jpg', 'Leica Geosystem, 2015', 'Slikanje instrumenta je omogočil Geoservis d.o.o', 'Leica MultiStation MS50\r\n\r\n\r\nInstrument švicarskega podjetja Leica Geosystem je bil v sredini leta 2015 najbolj vsestranski tahimeter na svetu. Leica MS50 sloni na tehnologiji mergeTEC, ki v eni kompaktni napravi združuje laserksi skener hitrosti 1000 točk/s, vrhunski tahimeter, slikovno podporo in združljivost z GNSS-sprejemniki Leica. MergeTEC predstavlja tudi enotno podatkovno bazo za vse podatke iz različnih senzorjev.\r\n\r\nOstali podatki:\r\n- natančnost merjenja kotov je 1\'\'\r\n- merjenje dolžin s pomočjo reflektorja je od 1.5 do 10.000 m\r\n- brez reflektorja  od 1.5 do 2000 m\r\n\r\nSamodejno ostrenje slike, ki se iz daljnogleda projecira na barvni VGA, na dotik občutljiv zaslon, osvetljen v obeh krožnih legah. Doseg samodejnega viziranja je od 600 do 1000 m, odvisno od tipa prizme. Samodejno iskanje reflektorja traja do 5 sekund do dolžine 300 m. Avtonomija delovanja 7-9 ur, masa skupaj z baterijo je 7.6 kg. Upravljanje instrumenta omogočajo 3 neskončni vijaki.', '2020-12-09 16:45:12', 0, 1, NULL, 2015),
(31, 'teodolit28.jpg', 'Miller Innsbruck, 1920', 'Instrument hrani Fakulteta za gradbeništvo in geodezijo pri Univerzi v Ljubljani', 'Odčitavanje horizontalnega kroga teodolita, ki je zaščiten v kovinskem ohišju, omogočata dva mikroskopa z mikrometrsko razdelbo, ki sta nameščena diametralno nasproti. Natančnost odčitavanja kotov je 1 minuta. Vertikalni krog, katerega 360-stopinjska razdelba je nanesena na kovinskem krogu, ni zaščiten. Odčitavanje kotov omogočata nonija, nad katerim sta nameščeni lupi. Natančnsot odčitavanja vertikalnega kota je 1 minuta, nonij je razdeljen na 10 enot. Instrument sodi v začetek 20. let prejšnjega stoletja.  V daljnogledu je nameščen Reichenbachov nitni križ, daljnogled ima izvlečeni okular. Na daljnogledu je nameščena nivelacijska libela, ob vertikalnem krogu tudi zavarovalna libela. Z instumenti tega tipa so se opravljale meritve do sredine 60. let prejšnjega stoletja. ', '2020-12-09 16:54:44', 0, 1, NULL, 1920),
(32, 'teodolit29.jpg', 'Rudolf & August Rost, Wien 1920', 'Instrument je v zasebni zbirki Gašperja Dimca iz Domžal', 'Teodolit spada med nonijske teodolite iz 20. let prejšnjega stoletja. Instrument ima oba kroga vgravirana na kovini (srebru), oba kroga sta zaščiteni pred vremenskimi vplivi. Razdelba na krogih je 20-minutna. Natančnost odčitavanja krogov omogočata po dva nonija, ki sta diametralno nameščeni na ohišje horizontalnega in vertikalnega kroga. Za lažje odčitavanje sta nad noniji nameščene lupe. Za horizontiranje instrumenta je na ohišju/alhidadi nameščena cevna libela. Na daljnogledu s 17-kratno povečavo in vgraviranim Reichenbachovim nitnim križem je nameščena nivelacijska libela. Določanje mesta čitanja na vertikalnem krogu omogoča zavarovalna libela.', '2020-12-09 17:02:00', 0, 1, NULL, 1920),
(33, 'teodolit30.jpg', 'Wild Heerbrugg, 1924', 'Instrument hrani podjetje Geoservis d.o.o', 'Wild T2\r\n\r\nTeodolit je prvi iz serije instrumentov Wild T2. Izdelan je bil leta 1924. Vrhunski dosežek Wildovih konstruktorjev se je odražal v natančnem sekundnem instrumentu z vgrajenimi steklenimi diski. Premer horizontalnega kroga je bil 90 mm in vertikalnega 45 mm. Prvič se je pri instrumentih pojavil mikroskop za odčitavanje kotov vzporedno z okularjem daljnogleda. Razdelba kotov je vgravirana z natančnostjo 20 sekund, s pomočjo vgrajenega mikrometra je omogočeno neposredno odčitavanje na sekundo natančno, z oceno pa na 0.1 sekunde. Instrument je omogočal osvetlitev horizontalnih in vertikalnih krogov tudi z umetno svetlobo.', '2020-12-09 17:12:13', 0, 1, NULL, 1924),
(34, 'nivelir1.jpg', 'Breihaupt & Sohn, Kassel, 1920', 'Arhivski primer hrani Fakulteta za gradbeništvo in geodezijo pri Univerzi v Ljubljani', 'To je nivelir z nivelacijsko libelo, ki je nameščena pod daljnogledom instrumenta. V daljngoledu z notranjim fokusiranjem je nameščen trinitni križ. Instrumentu je dodan horizontalni limb. Natančnost odčitavanja horizontalnih kotov je 1 minuta, kar omogoča nonij, ki je razdeljen na 30 enot. Tovrstne nivelirje so izdelovali v začetku 20. leta prejšnjega stoletja.', '2020-12-09 20:34:59', 0, 3, NULL, 1920),
(35, 'nivelir2.jpg', 'Carl Zeiss Jena, 1930', 'Nivelir hrani Fakulteta za gradbeništvo in geodezijo pri Univerzi v Ljubljani', 'Nivelir sodi v leta pred drugo svetovno vojno. Ima vgrajen sistem prizem, ki operaterju omogoča koincidiranje libele s pomočjo razdeljenega mehurčka. Za grobo horizontiranje ima dozno libelo. Pri tem instrumentu je mogoče daljnogled skupaj z reverzijsko libelo vred zavrteti okoli njegove podolžne/vizurne osi za 180 stopinj. V obeh legah daljnogleda (libela levo in libela desno) na lati dobimo dva neodvisna odčitka, katerih aritmetična sredina določa odsek na lati.', '2020-12-09 20:40:47', 0, 3, NULL, 1930),
(36, 'nivelir3.jpg', 'Carl Zeiss Jena, 1950', 'Instrument hranijo na Območni geodetski upravi Novo mesto', 'Carl Zeiss Ni 060\r\n\r\nNivelir Ni 060, iz serije ekonomičnih instrumentov, odlikuje velika natančnost  vseh optičnih in mehaničnih delov. Je majhen, lahek, zelo odporen in omogoča enostavno rokovanje. Uporabljal se je za določanje višin in snemanje enostavnih vzdolžnih in prečnih profilov v gradbeništvu, kar je omogočala njegova natančnost ±5 do 6 mm na 1000 m dvojnega nivelmana. Instrument se je pojavil na tržišču takoj po drugi svetovni vojni. Daljnogled, v katerega je vgrajen Reicehenbachov nitni križ, omogoča 19-kratno povečavo.', '2020-12-09 20:51:31', 0, 3, NULL, 1950),
(37, 'nivelir4.jpg', 'HA-1, 1963', 'Instrument hrani glavni urad Geodetske uprave Republike Slovenije.', 'Precizni nivelir je bil izdelan leta 1963 v ZSSR. Optična razdeljenost mehurčka nivelacijske libele povečuje natančnost za 3 do 5-krat v primerjavi s predhodniki. Za precizno niveliranje je vgrajen optični mikrometer, ki z lomljenjem vizure omogoča natančno viziranje (v okularju daljnogleda je zaradi uporabe planparalelne plošče v desetinkah milimetra viden podatek razlike med vrednostjo, ki jo beleži horizontalna vizura, in vrednostjo pomika vizure na okroglo centimetrsko oznako na vertikalni lati). Pred iznajdbo kompenzacijskih nivelirjev so tovrstni nivelirji sodili v vrh natančnosti. Slaba stran vseh takih nivelirjev pa je bila neprestana skrb za koincidiranje nivelacijske libele. Arhivski primerek je sorazmerno težak in neroden instrument-', '2020-12-09 20:59:21', 0, 3, NULL, 1963),
(38, 'nivelir5.jpg', 'Hildebrand, Freiberg na Saškem', 'Instrument hrani Naravoslovnotehniška fakulteta pri Univerzi v Ljubljani', 'Max Hildebrand, prej August Lingke & Co.\r\n\r\nNivelir z napisom na ohišju \"Max Hildebrand, fruher August Lingke & Co. Freiberg in Sachsen\" sodi v čas konca 19. stoletja. Instrument so razvili v znani finomehanični delavnici, ki jo je vodil Max Hildebrand. Pod daljnogledom z zunanjim fokusiranjem je nameščena nivelacijska libela, za grobo horizontiranje ima nivelir nameščeno dozno libelo.', '2020-12-09 21:03:30', 0, 3, NULL, 1890),
(39, 'nivelir6.jpg', 'Hildebrand - Wichmann - Werke, Freiberg, 1900', 'Arhivski primerek hrani Fakulteta za gradbeništvo in geodezijo pri Univerzi v Ljubljani', 'Hildebrand - Wichmann - Werke\r\n\r\nNivelir je bil izdelan v začetku prejšnjega stoletja. Nad daljnogledom ima nameščeno nivelacijsko libelo. V tistem času se je instrument uporabljal za merjenje vseh vrst nivelmanskih vlakov.', '2020-12-09 21:06:37', 0, 3, NULL, 1900),
(40, 'nivelir7.jpg', 'Officine Galileo, 1935', 'Instrument hrani Fakulteta za gradbeništvo in geodezijo pri Univerzi v Ljubljani', 'Nivelir Officine Galileo je proizvod italijanskega podjetja, ki je proizvajalo znanstvene instrumente s sedežem v Firencah. Nivelir ima vgrajen sistem prizem, ki operaterju omogoča koincidiranje libele s pomočjo razdeljenega mehurčka in možnost obračanja daljnogleda okoli horizontalne osi. Po natančnosti sodi med enostavne nivelirje in nivelirje srednje natančnosti. Instrument ima vgrajen horizontalni krog, katerega opazovanje omogoča mikroskop z vgrajenim mikrometrom. Izdelan je bil v sredini 30. let prejšnjega stoletja.', '2020-12-09 21:11:18', 0, 3, NULL, 1935),
(41, 'nivelir8.jpg', 'Otto Fennel, Kassel, 1930', 'Instrument hrani glavni urad Geodetske uprave Republike Slovenije', 'To je nivelir z nivelacijsko libelo, katere vrhunjenje se opazuje v okularju daljnogleda, ki sloni na tehnološki rešitvi posebnega sistema prizem, ki optično razdeli mehurček libele tako, da kaže sliki obeh krajev libele, ko vrhunita, v isti ravnini. V okularju daljnogleda je viden tudi podatek (razlika v desetinkah mm med vrednostjo, ki jo beleži horizontalna vizura, in pomikom vizure na okroglo oznako - cm na vertikalni lati), ki se doseže s premikom planparalelne plošče s pomočjo mikrometrskega vijaka. Okular daljnogleda je tako podeljen na območje viziranja (na sredini okularja), opazovanje vrhunjenja mehurčka (levi del okularja) in območje opazovanja pomika vizure (desni del okularja). Nivelir ima vgrajen nivelacijski vijak, ki je do odkritja kompenzacijski nivelirjev omogočal precizno vrhunjenje nivelacijske libele. Pred iznajdbo kompenzacijskih nivelirjev so tovrstni nivelirji sodili v vrh natančnosti. Slaba stran vseh takih nivelirjev pa je neprestana skrb za koincidiranje nivelacijske libele. Arhivski primerek je sorazmerno težak in neroden instrument. Izdelan je bil med obema svetovnima vojnama.', '2020-12-09 21:22:27', 0, 3, NULL, 1930),
(42, 'nivelir9.jpg', 'Wild Heerbrugg, 1950', 'Instrument je v zasebni zbirki Gašperja Dimca iz Domžal.', 'Wild št. 21727\r\n\r\nNivelir ima vgrajen sistem prizem, ki operaterju omogoča koincidiranje libele s pomočjo razdeljenega mehurčka. Koincidiranje libele operater opazuje prekk trirobne prizme, ki je nameščena nad nivelacijsko libelo. Grobo horizontiranje omogoča dozna libela. Po natančnosti sodi med enostavne nivelirje. Instrument ima za uravnavanje nivelacijske libele mikrometrski vijak, zatič za grobo zaustavljanje vrtenja daljnogleda okrog vertikalne osi in poseben vijak za precizno naravnavanje na lato. V daljnogledu ima vgrajen Reichenbachov nitni križ in stekleni horizontalni krog z razdelbo v gradih, ki se odčitava s pomočjo mikroskopa, nameščenega neposredno ob okular daljnogleda. Nivelir je iz 50. let prejšnjega stoletja.', '2020-12-09 21:35:10', 0, 3, NULL, 1950),
(43, 'nivelir10.jpg', 'Otto Fennel, Kassel, 1920', 'Instrument hrani Fakulteta za gradbeništvo in geodezijo pri Univerzi v ljubljani', 'To je nivelir z nivelacijsko libelo, katere vrhunjenje se opazuje v okularju daljnogleda, ki sloni na tehnološki rešitvi posebnega sistema prizem, ki optično razdeli mehurček libele tako, da kaže sliki obeh krajev libele, ko vrhunita, v isti ravnini. Za hrobo horizontiranje ima instrument vgrajeno dozno libelo. Za poravnanje libele je pod okularjem daljnogleda nameščen nivelacijski vijak. Arhivki eksponat je sorazmerno težak in neroden instrument. Izdelan je bil po prvi svetovni vojni.', '2020-12-09 21:40:37', 0, 3, NULL, 1920),
(44, 'ostalo1.jpg', 'Izrisovalnik izohips - razsnolka', 'Orodje hrani glavni urad Geodetske uprave Republike Slovenije', 'To je mehanska pripravaza izrisovanje izohips. Izohipsa je krivulja na zemljevidu, ki veže kraje z isto nadmorsko višino. S pomočjo te naprave je risar ali kartograf na načrtu ali zemljevidu povezal vse točke z isto nadmorsko višino z zvezno, gladko črto. Nove izmere topografskih načrtov po drugi svetovni vojni so bile večinoma izdelane z ročnim kartiranjem in izrisovanjem linij. Razsnolka je omogočala izdelavo ličnih izdelkov - s to napravo so se kompenzirale vse težave tresoče ali ne preveč natančne roke', '2020-12-09 21:55:53', 0, 4, NULL, 0),
(45, 'ostalo2.jpg', 'Koordinatograf, polarni', 'Orodje hrani glavni urad Geodetske uprave Republike Slovenije', 'Kartirni pripomoček za nanašanje kotov z dvema nonijema. To je naprava za kartiranje detajla, posnetega s tahimetrično metodo. Napravo sestavlja 360-stopinjski krog z vgravirano razdelbo, prek katerega je nameščena kovinska ročica z vgravirano razdelbo v različnih merilih. Za nanašanje kotov - smeri sta h krogu dodana dva nonija, nad katerima se premikajoče iz enega na drugi nonij prilagaja lupa. Na kovinskem merilu je na posebnem drsniku nameščen linijski nonij, ki omogoča nanašanje dolžin.', '2020-12-09 22:11:52', 0, 4, NULL, 0),
(46, 'ostalo3.jpg', 'Gebruder Fromme, 1950', 'Instrument hrani podjetje Geoservis d.o.o', 'Klinometer Gebruder Fromme\r\nDaljnogled instrumenta ima Reichenbachov nitni križ, vertikalni krog se odčitava s pomočjo nonija in je razdeljen na 30 sekund. Obseg označene razdelbe na verikalnem krogu je 40 stopinj od vertikale na vsako stran.', '2020-12-10 22:56:32', 0, 4, NULL, 1950),
(47, 'ostalo4.jpg', 'Ertel & Sohn - klinometer, 1950', 'Instrument hrani Tehniški muzej Slovenije', '<p>Instrument sodi v 50. leta prejšnjega stoletja. Ta orodja se pri vzdrževanju zemljiškega katastra praviloma niso uporabljala. Na samem ravnilu ima nameščen kompas in dozno libelo. Daljnogled je opremljen z nivelacijsko libelo. 360-stopinjska razdelba vertikalnega kroga je vgravirana na krogu z 10-minutno razdelbo. Odčitavanje na minuto natančno omogočata dva nonija in lupi. Za določanje mesta čitanja na vertikalnem krogu je nameščena zavarovalna libela.</p>', '2020-12-09 22:59:33', 0, 4, NULL, 1950),
(48, 'ostalo5.jpg', 'Otto Fennel und Sohn, Kassel, 1950', 'Instrument hrani glavni urad Geodetske uprave Republike Slovenije', 'Fennelov kipregel iz leta 1950 je opremljen z daljnogledom, kot ga ima avtoredukcijski tahimeter Hammer-Fennel, in tako omogoča neposredno odčitavanje na lati reduciranih dolžin in relativnih višinskih razlik. V daljnogledu se vidijo na levi strani vidnega polja krivulje, na desni strani pa opazovani detajl. V objektivu je samo horizontalna nit. Daljnogled se navizira na lato na ničleno točko (običajno 2.4 m nad zemljo), ob krivuljah pa se odčitavajo horizontalne dolžine in relativne višinske razlike. Instrument ima tudi vertikalni krog. Garnitura je sestavljena iz paralelnega pomičnega ravnila dolgega 51.5 cm, dozne libele in busole za orientacijo. Risalna miza s priborom za postavitev in centriranje, na katero se s štirimi vijaki pričvrsti lesena plošča, je spojena z glavo stativa s centralnim vijakom. \r\n\r\nAvtoredukcijski instrument se je na našem območju uporabljal za terensko dopolnjevanje topografsko-fotogrametričnih posnetkov, še posebej v hribovitem pdoročju. Podatki, pridobljeni s tem instrumentom, so bili bistveno boljši, kot pa jih je omogočal diopter.', '2020-12-09 23:29:08', 0, 4, NULL, 1950),
(49, 'ostalo6.jpg', 'Tahimetrično računalo', 'Pripomoček hrani glavni urad Geodetske uprave Republike Slovenije', 'Krožno kovinsko tahimetrično računalo je Gebruder Fromme. Zgodovina tega pripomočka sega v 17. stoletje, v čas prvih logaritmičnih računal. Kot redni tehnični pripomoček pa so se tovrstni izdelki pojavili konec 19. stoletja. Na krogu je nanesena logaritmična razdelba za vrednosti poševno izmerjenih dolžin. Na polkrožnem noniju je razdelba za cos2a in sin2a. Glede na to, da so se s pomočjo trinitnih razdeljemerov (Reichenbach) na lati odčitavale poševne dolžine, se je za nadaljnje obdelave in kartiranja, s pomočjo krožno kovinskega tahimetričnega računala, na enostaven in hiter način iz poševne dolžine in višinskega kota dalo izračunati horizontalno dolžino in višinsko razliko.', '2020-12-09 23:36:38', 0, 4, NULL, 0),
(50, 'ostalo7.jpg', 'Vektor - tahigraf', 'Orodje hrani glavni urad Geodetske uprave Republike Slovenije', 'Namenjen je za nanašanje vektorjev, to je dolžin in določenih smeri. Takšen način kartiranja se opravlja na podlagi izmer busolnih poligonskih vlakov, žiro kompasa in vlakov z geodetsko orientacijo. Pri poligonih v gozdovih in jamskem merjenju s to napravo dosežemo neverjetno hitrost kartiranja. Neizbežne  majhne netočnosti kartiranja se pri tej napravi ne prenašajo na naslednjo točko, saj se na vsaki točki vedno ponovno orientira proti severu.', '2020-12-09 23:40:21', 0, 4, NULL, 0),
(51, 'ostalo8.jpg', 'Računarski stroj', 'Računarski stroj hrani Območna geodetska uprava Slovenj Gradec', 'Mehanski računski stroj Calcorex. Stroj Calcorex so v TRS proizvajali v 70. letih prejšnjega stoletja.', '2020-12-09 23:43:18', 0, 4, NULL, 0),
(52, 'ostalo9.jpg', 'Pisalni stroj', 'Pisalni stroj hrani glavni urad Geodetske uprave Republike Slovenije', 'Prvi pisalni stroj je leta 1714 patentiral Anglež Henry Mill, vemdar ni potjeno, da je stroj tudi izdelal. V Ameriki pa je ameriški izumitelj in geodet William Austin Burt leta 830 izdelal prvi pisalni stroj, ki je bil že prethodnik poznejših strojev. Komercialni uspeh na tem področju se je po številnih vmesnih patentih in poizkusih začel s praktično delujočimi pisalnimi stroji po letu 1867. Elektronski pisalni stroj z lastnim elektronskim pomilnikom za shranjevanje teksta se je pojavil na trgu leta 1978.', '2020-12-09 23:49:58', 0, 4, NULL, 0),
(53, 'ostalo10.jpg', 'Starke & Kammerer, 1900 - klinometer', 'Klinometer hrani glavni urad Geodetske uprave Republike Slovenije', 'Klinometer je pripomoček za merjenje v gradbeništvu, predvsem za določanje ustreznih naklonov. Pripomoček daje podatke v odstotkih.', '2020-12-09 23:54:30', 0, 4, NULL, 1900),
(62, 'ostalo11.jpg', 'Polarni planimeter Amsler', 'Geodetski pripomoček za računanje in merjenje površin hrani Območna geodetska uprava Novo mesto.', '<p>Geodetsko orodje za za določanje površin na kartah in načrtih sestoji iz dveh krakov (polarnega in pomičnega), ki sta med seboj povezana prek zgloba in registrirne naprave z nonijem za natančno odlizavenje podatka na razdelbi. Na enem koncu polarnega kreaka je obtežitev z iglo za pričvrstitev na podlago. Na koncu pomičnega kraka je lupa z markico v sredini. Markica v lupi služi za vodenje pomičnega kraka po konturi parcele, katere površino želimo določiti.</p>', '2020-12-23 10:24:56', 0, 4, NULL, 0),
(63, 'ostalo12.jpg', 'Koordinatograf', 'Koordinatograf \"Čemus\" hrani Območna geodetska uprava Novo mesto', '<p>Koordinatograf je ročni pripomoček za kartiranje geodetskih posnetkov oz. meritev, posnetih po ortogonalni metodi. Koordinatograf je sestavljen iz daljše (abscisne) ročice in krajše (ordinate) ročice, pravokotno na abscisno os. Na ročicah je vgravirana razdelba v merilu. Povečano natančnost nanašanja podatkov omogoča nonij. </p>', '2020-12-23 11:20:26', 0, 4, NULL, 0),
(64, 'ostalo13.jpg', 'Logaritmično računalo', 'Logaritmično računalo hrani Območna geodetska uprava Novo mesto', '<p>Logaritme je prvi objavil škotski lord John Napier leta 1614, potem ko je dvajset let pripravljal tebele logaritmov, ki so omogočale izvajanje množenja in deljenja števil s seštevanjem in odštevanjem njihovih logaritmov. To je bil temelj za razvoj logaritmičnih računal. Za izumitelja logaritmičnega računala velja angleški učenjak William Oughtred, ki je leta 1625 začel izvajati račune z medsebojnim premikanjem dveh meril. Logaritmična računala se z leti po osnovnem dizajnu niso bistveno spreminjala, temveč so sledila potrebam trga na vseh področjih znanosti in tehnologije. Kot nepogrešljiv pripomoček se je uporabljal v hidravliki, elektrotehniki, medicini, trigonometriji, astronomiji, vojski, poslovno finančnem svetu in na drugih inženirskih in strokovnih področjih. S pojavom elektronskih kalkulatorjev se je začel hiter zaton uporabe tega pripomočka v praksi. </p><p>Logaritmično računalo je računski pripomoček za hitro izračunavanje določenih parametrov, kot so izračun skrčka, pretvorbe kotnih funkcij do določene natančnosti.</p><p>Za uporabo v geodeziji imajo logaritmična računala del skale prilagojen za račun tahimetrije, saj omogočajo izračun tangens in sinus kota, izraženega v stopinjah.</p>', '2020-12-23 11:54:48', 0, 4, NULL, 0),
(65, 'ostalo14.jpg', 'Natezalka', 'Orodje hrani glavni urad Geodetske uprave Republike Slovenije', '<p>Naprava za napenjanje merskih trakov je pripomoček, ki je izdelan iz držala, na katerega je pritrjena vzmet. Pri komprariranju (umerjanju) merskih trakov, je treba merski trak napeti s tako sliko, kot jo je v specifikaciji predvidel proizvajalec. Na posebni napravi - komparatorju -  se je ob napenjanju traku s predpisano silo odčital odklon od dolžine traku, ki ga je jamčil proizvajalec. Na raztezke merskega traku so vplivale večkratne nepravilne sile napenjanja, kakovost materiala, mehanske poškodbe in sveda temperatura.</p>', '2020-12-23 12:03:43', 0, 4, NULL, 0),
(66, 'teodolit31.jpg', 'Hildebrand-Wichmann-Werke, 1930', 'Instrument hranijo v Muzeju premogovništva Slovenije v Velenju', '<p>Instrument že uporablja steklene kroge, odčitavanje vertikalnega in horizontalnega kota omogoča mikrometer nameščen ob okularju daljnogleda. Daljnogled ima 23 - kratno povečavo, v daljnogledu je nameščen trinitni Reichenbachov nitni križ. Natančnost odčitavanja kotov je 1 minuta. </p><p>Instrument se pojavi pri vzdrževanju zemljiškega katastra pri Vrhniki, Kopru, Velenju in drugod, vendar je iz podatkov arhiva razvidno, da so bili ti instrumenti še starejšega datuma. Po vsej verjetnpsti izhajajo instrumenti, ki so se uporabljali v tistem času, iz obdobja med letoma 1910 in 1920.</p>', '2020-12-23 12:40:36', 0, 1, NULL, 1930),
(67, 'teodolit32.jpg', 'Fennel Kassel, 1925', 'Teodolit hrani Naravoslovnotehniška fakulteta pri Univerzi v Ljubljani', '<p>Odčitavanje krogov omogočajo posebni mikroskopi z mikrometrsko razdelbo petih minut. Natančnost odčitavanja obeh krogov je 1 minuta. Na daljnogledu z Reichenbachovim razdeljemerom je nivelacijska libela. Daljnogled ima zunanje fokusiranje. Za uravnavanje vertikalnega kroga ima zavarovalno libelo in posebni libeli na ohišju za horizontiranje samega instrumenta. Oba kroga sta zaščitena v kovinskem ohišju. Pri transportu se zgornji del instrumenta (daljnogled in vertikalni krog) ločeno shranjuje v prirejeno transportno embalažo. Instrument ima tudi repeticijski vijak in dve vrtljivi osi, tj. vrtilno os alhidade in vrtilno os limba.</p>', '2020-12-23 12:46:10', 0, 1, NULL, 1925),
(68, 'teodolit33.jpg', 'Carl Zeiss Jenna, 1930', 'Delno restavrirani arhivski primerek hrani Geodetska družba d.o.o', '<p>Največjo serijo v proizvodnji je po prvi svetovni vojni doživel teodolit Th IV, ki je sledil predhodniku in so ga uporabljali povsod po svetu. Teodolit je bil izdelan v 30. letih prejšnjega stoletja. Ima že oba kroga iz stekla, daljnogled omogoča 28 - kratno povečavo, v njem je vgrajen Reichenbachov nitni križ, neposredno ob okular daljnogleda je nameščen mikroskop za odčitavanje obeh krogov. Stekleni krog je razdeljen na intervale z 1 stopinjo. Natančnost odčitavanja je 1 minuta, z oceno na desetinko minute, kar omogoča mikrometrska razdelba.</p>', '2020-12-23 12:50:59', 0, 1, NULL, 1930),
(69, 'teodolit34.jpg', 'Carl Zeiss Jena, 1924', 'Instrument hrani Tehniški muzej Slovenije', '<p>V podjetju Carl Zeiss Jena so že leta 1924 proizvedli prvi teodolit Th 1, ki je imel stakleni limb. V proizvodnji je bila taka oblika instrumenta do 1930. Ko je Heincrich Wild zasnoval Th 1, je imel pred seboj cilj, da instrument izpolnjuje naslednje zahteve:</p><ul><li>najmanjše možne mere in ,aso</li><li>priročno upravljanje</li><li>majhna občutljivost pri prevozih</li><li>odpornost pred dežjem in prahom</li><li>vidna kombinacija slik dveh nasprotnih delov kroga v enem okularju</li><li>projiciranje slike nasprotnih točk kroga skozi votlo os in s tem doseganje popolnega zaprtja krogov</li><li>razvoj visoko občutljivega mikrometra, ki bi omogočal neposredno odčitavanje aritmetične sredine nasprotnih/diametralnih točk kotov</li></ul><p>Vse to mu je pri tem instrumentu uspelo. Instrument omogoča odčitavanje horizontalnega in vertikalnega kroga neposredno z 20 - minutno natančnostjo, z ocenopa z 2 - minutno natačnostjo. Dodan je poseben repeticijski vijak. Odčitavanje kotov omogoča poseben mikroskop, ki je gibljiv, da se prilagaja krožni legi daljnogleda. Za horizontiranje instrumenta sta nameščena dve cevni libeli.</p>', '2020-12-23 13:08:46', 0, 1, NULL, 1924),
(70, 'teodolit35.jpg', 'Carl Zeiss Jenna, 1930', 'Instrument hrani glavni urad Geodetske uprave Republike Slovenije', '<p>Teodolite z oznako Th II so v podjetju Carl Zeiss Jena izdelovali v letih 1930 do 1941. Visoko (sekundno) natančnost merjenja horizontalnih in vertiklanih kotov sta omogočana nasteklo gravirana krožna razdelba in vgrajeni mikrometer. Za ekonomično in enostavno rokovanje je bil mikroskop za odčitavanje kotov nameščen neposredno ob okular daljnogleda. Instrument je bil primeren za triangulacije II., III. in IV. reda, za precizne poligone in astronomska opazovanja.</p>', '2020-12-23 13:12:33', 0, 1, NULL, 1930);
INSERT INTO `muzej` (`id`, `cover_photo`, `title`, `short_description`, `content`, `created_at`, `deleted`, `category`, `main_category`, `year`) VALUES
(71, 'nivelir11.jpg', 'Neuhofer & Sohn, 1890', 'Instrument hrani glavni urad Geodetske uprave Republike Slovenije', '<p>Nivelir ima dva vznožna vijaka za horizontiranje. Izdelan je bil v zadnjih letih 19. stoletja. V 19. stoletju so večinoma izdelovali instrumente z natično glavo za poseben \"čepni\" stativ. Tovrstne instrumente so druga podjetja začela proizvajati že pred letom 1860. Na ozemlju sedanje Slovenije so se v praksi uporabljali vse do prve svetovne vojne. Za grobo horizontiranje sta v podnožju instrumenta nameščena dva vijaka. Za fino horizontiranje nivelacijske libele se uporablja poseben nivelacijski vijak, nameščen spredaj, neposredno pred daljnogledom.</p>', '2020-12-23 13:18:54', 0, 3, NULL, 1890),
(72, 'nivelir12.jpg', 'W. Ottway & Co. Ealing, 1904', 'Instrument je v zasebni zbirki', '<p>Nivelir sodi v zgodnja leta 20. stoletja. Daljnogled je nameščen neposredno nad kompasom. Posebnost izvedbe teh instrumentov je, da imajo zunanje fokusiranje, in sicer je, za razliko od proizvajalecv iz celinskega dela Evrope, pomičen objektiv in ne okular. Svojevrstna (nenavdana za proizvajalce iz celinskega dela Evrope) je tudi rešitev za odčitavanje podatka na kompasu - to omogoča posebna triroba prizma, nameščena na ohišju nivelirja ob obodu busole.</p>', '2020-12-23 13:23:04', 0, 3, NULL, 1904),
(73, 'nivelir13.jpg', 'Rudolf & August Rost, 1920', 'Arhivski primerek hrani Fakulteta za gradbeništvo in geodezijo pri Univerzi v Ljubljani', '<p>Prvi primerki podobnih instrumentov so bili izdelani v podjetju Carl Zeiss Jena v letu 1908, konstruktor teh instrumentov je bil Heinrich Wild. Pri tem instrumentu je mogoče daljnogled  z reverzijsko libelo vred zavrteti okoli njegovo podolžne/vizurne osi za 180 stopinj. To je nivelacijski instrument s cilindrično izvedbo vertikalne osi, z vrtljivim daljnogledom in z reverzijsko libelo (libela, ki ima na zgornji in spodnji strani brušeno cevko pod enakim krivinskim polmerom in na spodnji in zgornji strani cevke označbo znamke libele). Za grobo horizontiranje ima instrument dozno libelo. Instrumentu je dodan horizontalni krog; natančnost odčitavanja horizontalnega kroga je 1 minuta, kar omgoča nonij z 20 - minutno razdelbo, nad katerim  je nameščena lupa. Daljnogled ima še izvelečni okular. Instrument je bil izdelan v začetku 20. let prejšnjega stoletja.</p>', '2020-12-23 13:30:39', 0, 3, NULL, 1920),
(74, 'nivelir14.jpg', 'Starke & Kammerer, 1930', 'Instrument je del Slovenske geodetske zbirke na gradu Bogenšprek.', '<p>Nivelir sodi v 30. leta prejšnjega stoletja. Namenjen je bil za merjenje nivelmanov nižjega reda in za merjenje v gradbeništvu. Za horizontiranje instrumenta sta na ohišje/alhidadi nameščeni dve medsebojno pravokotno cevni libeli. Pogled na nivelacijsko libelo omogoča ogledalo, ki je nameščeno nad nivelacijsko libelo iznad daljnogleda nivelirja. Naravnavanje koincidiranja nivelacijske libele omogoča koincidenčni vijak, nameščen na sprednji strani, pod daljnogledom instrumenta. Nivelir sodi v  skupino instrumentov za čepni stativ.</p>', '2020-12-23 13:35:05', 0, 3, NULL, 1930);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `muzej`
--
ALTER TABLE `muzej`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `muzej`
--
ALTER TABLE `muzej`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=75;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
